-- P00-02: initial foundation. Later domains add their own migrations.
-- Future-domain IDs are reserved TEXT fields; their FKs arrive with their domain migration.
CREATE TABLE profiles (
id TEXT PRIMARY KEY, display_name TEXT NOT NULL, avatar_file_id TEXT,
locale TEXT NOT NULL CHECK(locale='zh-CN'), timezone TEXT NOT NULL,
created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER,
singleton INTEGER NOT NULL DEFAULT 1 UNIQUE CHECK(singleton=1)
);
CREATE TABLE settings (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, scope_type TEXT NOT NULL CHECK(scope_type IN ('profile','project','session')), scope_id TEXT NOT NULL, key TEXT NOT NULL, value_json TEXT NOT NULL CHECK(json_valid(value_json) AND json_extract(value_json,'$.schemaVersion') IS 1), UNIQUE(scope_type,scope_id,key));
CREATE TABLE provider_accounts (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, provider_id TEXT NOT NULL CHECK(provider_id IN ('codex-subscription','deepseek','hunyuan','xai','doubao')), label TEXT NOT NULL, auth_type TEXT NOT NULL CHECK(auth_type IN ('api_key','oauth')), credential_id TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('unconfigured','ready','expired','unavailable')), last_check_at INTEGER, last_error_code TEXT, priority INTEGER NOT NULL DEFAULT 0);
CREATE TABLE sessions (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, project_id TEXT, title TEXT NOT NULL, mode TEXT NOT NULL CHECK(mode IN ('chat','work')), active_branch_id TEXT REFERENCES branches(id) DEFERRABLE INITIALLY DEFERRED, temporary INTEGER NOT NULL DEFAULT 0 CHECK(temporary=0), settings_json TEXT NOT NULL CHECK(json_valid(settings_json) AND json_extract(settings_json,'$.schemaVersion') IS 1), archived_at INTEGER, last_activity_at INTEGER NOT NULL, unread_event_seq INTEGER NOT NULL DEFAULT 0);
CREATE TABLE branches (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, session_id TEXT NOT NULL REFERENCES sessions(id), parent_branch_id TEXT REFERENCES branches(id), fork_message_id TEXT REFERENCES messages(id), head_message_id TEXT REFERENCES messages(id), label TEXT NOT NULL);
CREATE TABLE messages (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, session_id TEXT NOT NULL REFERENCES sessions(id), branch_id TEXT NOT NULL REFERENCES branches(id), parent_message_id TEXT REFERENCES messages(id), role TEXT NOT NULL CHECK(role IN ('user','assistant','tool','system_note')), content_json TEXT NOT NULL CHECK(json_valid(content_json) AND json_extract(content_json,'$.schemaVersion') IS 1), status TEXT NOT NULL CHECK(status IN ('queued','streaming','final','interrupted','failed','cancelled')), provider_attempt_id TEXT, run_id TEXT);
CREATE TABLE message_versions (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, message_id TEXT NOT NULL REFERENCES messages(id), version INTEGER NOT NULL CHECK(version>0), content_json TEXT NOT NULL CHECK(json_valid(content_json) AND json_extract(content_json,'$.schemaVersion') IS 1), reason TEXT NOT NULL CHECK(reason IN ('edit','regenerate','restore')), source_version_id TEXT REFERENCES message_versions(id), UNIQUE(message_id,version));
CREATE TABLE drafts (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, session_id TEXT NOT NULL REFERENCES sessions(id), window_id TEXT NOT NULL, text TEXT NOT NULL, attachment_refs_json TEXT NOT NULL CHECK(json_valid(attachment_refs_json) AND json_extract(attachment_refs_json,'$.schemaVersion') IS 1), UNIQUE(session_id,window_id));
CREATE TABLE jobs (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, kind TEXT NOT NULL CHECK(kind IN ('blob.gc','data.backup')), entity_id TEXT, dedupe_key TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL CHECK(json_valid(payload_json) AND json_extract(payload_json,'$.schemaVersion') IS 1), status TEXT NOT NULL CHECK(status IN ('queued','running','completed','failed','cancelled','unknown')), attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at INTEGER NOT NULL, lease_owner TEXT, lease_epoch INTEGER NOT NULL DEFAULT 0, lease_expires_at INTEGER, cancel_requested_at INTEGER, result_ref TEXT, error_code TEXT);
CREATE TABLE budgets (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, owner_kind TEXT NOT NULL CHECK(owner_kind IN ('root','daily')), owner_id TEXT NOT NULL, limits_json TEXT NOT NULL CHECK(json_valid(limits_json) AND json_extract(limits_json,'$.schemaVersion') IS 1), reserved_tokens INTEGER NOT NULL DEFAULT 0 CHECK(reserved_tokens>=0), used_tokens INTEGER NOT NULL DEFAULT 0 CHECK(used_tokens>=0), active_ms INTEGER NOT NULL DEFAULT 0 CHECK(active_ms>=0), money_by_currency_json TEXT NOT NULL CHECK(json_valid(money_by_currency_json) AND json_extract(money_by_currency_json,'$.schemaVersion') IS 1), UNIQUE(owner_kind,owner_id));
CREATE TABLE blobs (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, sha256 TEXT NOT NULL UNIQUE CHECK(length(sha256)=64), relative_key TEXT NOT NULL UNIQUE, size_bytes INTEGER NOT NULL CHECK(size_bytes>=0), reference_count INTEGER NOT NULL DEFAULT 0 CHECK(reference_count>=0), state TEXT NOT NULL CHECK(state IN ('staged','ready','deleting')), media_type TEXT NOT NULL);
CREATE TABLE files (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, display_name TEXT NOT NULL, extension TEXT NOT NULL, mime TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('input','artifact','note')), folder_id TEXT, current_version_id TEXT REFERENCES file_versions(id) DEFERRABLE INITIALLY DEFERRED, status TEXT NOT NULL, source_type TEXT NOT NULL CHECK(source_type IN ('import','generated','url')), source_uri TEXT, original_path_display TEXT);
CREATE TABLE file_versions (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, file_id TEXT NOT NULL REFERENCES files(id), version INTEGER NOT NULL CHECK(version>0), blob_id TEXT NOT NULL REFERENCES blobs(id), size_bytes INTEGER NOT NULL CHECK(size_bytes>=0), sha256 TEXT NOT NULL, parser_version TEXT, parse_status TEXT NOT NULL, preview_status TEXT NOT NULL, created_by_run_id TEXT, UNIQUE(file_id,version));
CREATE TABLE grants (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, scope_kind TEXT NOT NULL CHECK(scope_kind IN ('once','session','persistent')), scope_id TEXT NOT NULL, tool_names_json TEXT NOT NULL CHECK(json_valid(tool_names_json) AND json_extract(tool_names_json,'$.schemaVersion') IS 1), resource_rules_json TEXT NOT NULL CHECK(json_valid(resource_rules_json) AND json_extract(resource_rules_json,'$.schemaVersion') IS 1), action_classes_json TEXT NOT NULL CHECK(json_valid(action_classes_json) AND json_extract(action_classes_json,'$.schemaVersion') IS 1), expires_at INTEGER, revoked_at INTEGER);
CREATE TABLE approvals (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, tool_call_id TEXT NOT NULL, task_version INTEGER NOT NULL CHECK(task_version>0), args_hash TEXT NOT NULL, resource_hash TEXT NOT NULL, content_version_hash TEXT NOT NULL, decision TEXT NOT NULL CHECK(decision IN ('pending','approved','rejected','expired','revoked')), expires_at INTEGER NOT NULL, decided_at INTEGER);
CREATE TABLE resource_links (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, resource_type TEXT NOT NULL CHECK(resource_type IN ('file','memory','web_source')), resource_id TEXT NOT NULL, owner_type TEXT NOT NULL CHECK(owner_type IN ('session','project','task')), owner_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('input','output','source')), pinned_version_id TEXT, UNIQUE(resource_type,resource_id,owner_type,owner_id,role));
CREATE TABLE deletion_tombstones (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0), deleted_at INTEGER, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, deleted_before_event_seq INTEGER NOT NULL, UNIQUE(profile_id,entity_type,entity_id));
CREATE TABLE events (id TEXT PRIMARY KEY,profile_id TEXT NOT NULL REFERENCES profiles(id),stream_id TEXT NOT NULL,seq INTEGER NOT NULL CHECK(seq>0),event_type TEXT NOT NULL,schema_version INTEGER NOT NULL CHECK(schema_version=1),task_version INTEGER,run_id TEXT,causation_id TEXT,payload_json TEXT  CHECK(payload_json IS NULL OR (json_valid(payload_json) AND json_extract(payload_json,'$.schemaVersion') IS 1)),payload_blob_id TEXT REFERENCES blobs(id),created_at INTEGER NOT NULL,UNIQUE(stream_id,seq));
CREATE TABLE outbox (id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES events(id) ON DELETE CASCADE,topic TEXT NOT NULL,payload_ref TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('pending','delivering','done')),attempts INTEGER NOT NULL DEFAULT 0,next_attempt_at INTEGER NOT NULL,lease_until INTEGER,lease_owner TEXT,lease_epoch INTEGER NOT NULL DEFAULT 0);
CREATE TABLE request_receipts (profile_id TEXT NOT NULL REFERENCES profiles(id),request_id TEXT NOT NULL,command TEXT NOT NULL,payload_hash TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('pending','completed','unknown')),reply_json TEXT  CHECK(reply_json IS NULL OR (json_valid(reply_json) AND json_extract(reply_json,'$.schemaVersion') IS 1)),expires_at INTEGER NOT NULL,PRIMARY KEY(profile_id,request_id));
CREATE TABLE backups (id TEXT PRIMARY KEY,profile_id TEXT NOT NULL REFERENCES profiles(id),manifest_path TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('pending','complete','failed')),created_at INTEGER NOT NULL,schema_version INTEGER NOT NULL,deleted_resource_ids_json TEXT NOT NULL CHECK(json_valid(deleted_resource_ids_json) AND json_extract(deleted_resource_ids_json,'$.schemaVersion') IS 1));
CREATE INDEX sessions_activity ON sessions(profile_id,project_id,archived_at,last_activity_at DESC,id);
CREATE INDEX messages_order ON messages(session_id,branch_id,created_at,id);
CREATE INDEX events_order ON events(stream_id,seq);
CREATE INDEX jobs_due ON jobs(status,next_attempt_at);
CREATE INDEX outbox_due ON outbox(state,next_attempt_at);
CREATE INDEX resource_owners ON resource_links(owner_type,owner_id,resource_type);
